import Config

# Set the environment
config :ehs_enforcement, :environment, :dev

# Debug Ash PubSub events
config :ash, :pub_sub, debug?: true

# Configure your database
config :ehs_enforcement, EhsEnforcement.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  port: 5434,
  database: "ehs_enforcement_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10,
  log: false  # Disable Ecto query logging

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :ehs_enforcement, EhsEnforcementWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: String.to_integer(System.get_env("PORT") || "4002")],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "+EKbytfOy1BQnufbCNiqYUKXzDQW1LARNYWKbXr0dxLE8jU+lVfeGL51f9S4mS4h",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:ehs_enforcement, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:ehs_enforcement, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :ehs_enforcement, EhsEnforcementWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/ehs_enforcement_web/(controllers|live|components)/.*(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :ehs_enforcement, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Configure logger to filter out noisy logs
config :logger,
  backends: [:console]
  # Note: Removed compile_time_purge_matching to allow debug logs after cleanup
  # Runtime filtering below still suppresses noisy Phoenix/Ecto logs

# Add runtime filtering for Phoenix socket logs and Ecto queries
config :logger, :default_handler,
  filters: [
    suppress_noisy_logs: {
      fn log_event, _opts ->
        case log_event do
          # Suppress Phoenix LiveView Socket logs
          %{meta: %{module: Phoenix.LiveView.Socket}} -> 
            :stop
          
          # Suppress Ecto query logs
          %{meta: %{module: module}} when is_atom(module) ->
            module_str = Atom.to_string(module)
            if String.starts_with?(module_str, "Elixir.Ecto.Adapters") do
              :stop
            else
              log_event
            end
          
          # Suppress specific message patterns
          %{msg: {:string, msg}} when is_binary(msg) ->
            cond do
              String.contains?(msg, "CONNECTED TO Phoenix.LiveView.Socket") -> :stop
              String.contains?(msg, "QUERY OK") -> :stop
              String.contains?(msg, "MOUNT EhsEnforcementWeb") -> :stop
              String.contains?(msg, "Broadcasting to topics") -> :stop  # Suppress verbose Ash PubSub broadcast logs
              String.contains?(msg, "QUERY ERROR") -> log_event  # Keep query errors
              true -> log_event
            end
          
          # Default: let the log through
          _ -> 
            log_event
        end
      end,
      :unused
    }
  ]

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include HEEx debug annotations as HTML comments in rendered markup
  debug_heex_annotations: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true,
  # Disable mount debug logging
  log_mount_errors: false

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

# Enable Ash PubSub debug mode for development
config :ash, :pub_sub, debug?: true
