import Config

# Enable SSL mode for production (required for secure session cookies)
config :ehs_enforcement, :force_ssl, true

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :ehs_enforcement, EhsEnforcementWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json",
  # Force SSL for secure session cookies (nginx handles SSL termination, but we need this for secure cookies)
  force_ssl: [hsts: true, rewrite_on: [:x_forwarded_host, :x_forwarded_port, :x_forwarded_proto]],
  # Use default Bandit configuration (no custom timeouts)
  http: []

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: EhsEnforcement.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Production logging configuration - FULL DEBUG MODE
config :logger,
  level: :debug,
  backends: [:console],
  compile_time_purge_matching: [
    [level_lower_than: :debug]
  ]

# Enable all Phoenix debugging
config :phoenix, :logger, true
config :phoenix, :plug_init_mode, :runtime

# Enable detailed LiveView logging
config :phoenix_live_view, :debug_heex_annotations, true

# Ash configuration for production - FULL DEBUG
config :ash, :disable_async?, false
config :ash, :pub_sub, debug?: true
config :ash_authentication, debug?: true

# Production environment marker
config :ehs_enforcement, :environment, :prod

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
