defmodule EhsEnforcement.Repo.Migrations.AddConsentSettings do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:events) do
      add :changed_attributes, :map, null: false, default: %{}
    end

    create table(:consent_settings, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :terms, :text, null: false
      add :groups, {:array, :text}, default: []
      add :consented_at, :utc_datetime_usec
      add :expires_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop table(:consent_settings)

    alter table(:events) do
      remove :changed_attributes
    end
  end
end
