defmodule EhsEnforcement.Repo.Migrations.AddEaOffenderFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:offenders) do
      add :company_registration_number, :text
      add :town, :text
      add :county, :text
      add :industry_sectors, {:array, :text}, default: []
    end
  end

  def down do
    alter table(:offenders) do
      remove :industry_sectors
      remove :county
      remove :town
      remove :company_registration_number
    end
  end
end
