defmodule EhsEnforcement.Repo.Migrations.AddAgenciesToOffenders do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:offenders) do
      add :agencies, {:array, :text}, default: []
    end
  end

  def down do
    alter table(:offenders) do
      remove :agencies
    end
  end
end
