defmodule EhsEnforcement.Repo.Migrations.AddSimpleSyncSessionsFinal do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:simple_sync_sessions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :session_id, :text, null: false
      add :sync_type, :text, null: false
      add :status, :text, null: false, default: "pending"
      add :target_resource, :text
      add :progress_stats, :map, default: %{}
      add :started_at, :utc_datetime_usec
      add :completed_at, :utc_datetime_usec
      add :duration_ms, :bigint
      add :config, :map, default: %{}
      add :initiated_by, :text
      add :estimated_total, :bigint
      add :actual_total, :bigint
      add :error_count, :bigint, default: 0
      add :last_error, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop table(:simple_sync_sessions)
  end
end
