defmodule EhsEnforcement.Repo.Migrations.AddEaParamsToScrapeSessions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:scrape_sessions) do
      add :agency, :text, null: false, default: "hse"
      add :date_from, :date
      add :date_to, :date
      add :action_types, {:array, :text}
    end
  end

  def down do
    alter table(:scrape_sessions) do
      remove :action_types
      remove :date_to
      remove :date_from
      remove :agency
    end
  end
end
