defmodule EhsEnforcement.Repo.Migrations.AddSyncTrackingResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:sync_sessions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :session_id, :text, null: false
      add :sync_type, :text
      add :source_type, :text, default: "airtable"
      add :target_resource, :text
      add :status, :text, default: "pending"
      add :total_records, :bigint, default: 0
      add :processed_records, :bigint, default: 0
      add :created_records, :bigint, default: 0
      add :updated_records, :bigint, default: 0
      add :existing_records, :bigint, default: 0
      add :error_records, :bigint, default: 0
      add :config, :map, default: %{}
      add :started_at, :utc_datetime
      add :completed_at, :utc_datetime
      add :estimated_completion_at, :utc_datetime
      add :error_message, :text
      add :error_details, :map
      add :initiated_by, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :agency_id,
          references(:agencies,
            column: :id,
            name: "sync_sessions_agency_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create table(:sync_progress, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :batch_number, :bigint, null: false
      add :batch_size, :bigint, null: false
      add :status, :text, default: "pending"
      add :records_processed, :bigint, default: 0
      add :records_created, :bigint, default: 0
      add :records_updated, :bigint, default: 0
      add :records_existing, :bigint, default: 0
      add :records_failed, :bigint, default: 0
      add :started_at, :utc_datetime
      add :completed_at, :utc_datetime
      add :error_message, :text
      add :error_details, :map
      add :retry_count, :bigint, default: 0
      add :source_ids, {:array, :text}
      add :failed_ids, {:array, :text}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :sync_session_id,
          references(:sync_sessions,
            column: :id,
            name: "sync_progress_sync_session_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    alter table(:sync_logs) do
      modify :agency_id, :uuid, null: true
      add :operation_type, :text
      add :resource_type, :text
      add :records_created, :bigint, default: 0
      add :records_updated, :bigint, default: 0
      add :records_existing, :bigint, default: 0
      add :records_failed, :bigint, default: 0
      add :error_details, :map
      add :error_count, :bigint, default: 0
      add :session_id, :text
      add :config_snapshot, :map
      add :processing_time_seconds, :bigint
      add :records_per_second, :decimal

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :sync_session_id,
          references(:sync_sessions,
            column: :id,
            name: "sync_logs_sync_session_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:sync_logs, "sync_logs_sync_session_id_fkey")

    alter table(:sync_logs) do
      remove :sync_session_id
      remove :updated_at
      remove :records_per_second
      remove :processing_time_seconds
      remove :config_snapshot
      remove :session_id
      remove :error_count
      remove :error_details
      remove :records_failed
      remove :records_existing
      remove :records_updated
      remove :records_created
      remove :resource_type
      remove :operation_type
      modify :agency_id, :uuid, null: false
    end

    drop constraint(:sync_progress, "sync_progress_sync_session_id_fkey")

    drop table(:sync_progress)

    drop constraint(:sync_sessions, "sync_sessions_agency_id_fkey")

    drop table(:sync_sessions)
  end
end
