defmodule EhsEnforcement.Repo.Migrations.DropCaseBreachColumns do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists index(:cases, [:offence_breaches], name: "cases_offence_breaches_gin_trgm")

    drop_if_exists index(:cases, [:offence_breaches], name: "cases_offence_breaches_index")

    alter table(:cases) do
      remove :offence_breaches_clean
      remove :offence_breaches
    end
  end

  def down do
    alter table(:cases) do
      add :offence_breaches, :text
      add :offence_breaches_clean, :text
    end

    create index(:cases, [:offence_breaches], name: "cases_offence_breaches_index")

    create index(:cases, [:offence_breaches],
             name: "cases_offence_breaches_gin_trgm",
             using: "GIN"
           )
  end
end
