defmodule EhsEnforcement.Repo.Migrations.CreateViolationResource do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:violations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :violation_sequence, :bigint
      add :case_reference, :text
      add :individual_fine, :decimal
      add :offence_description, :text
      add :legal_act, :text
      add :legal_section, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :case_id,
          references(:cases,
            column: :id,
            name: "violations_case_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create index(:violations, [:case_reference],
             name: "violations_case_reference_unique",
             unique: true
           )

    create index(:violations, [:case_id, :violation_sequence],
             name: "violations_case_sequence_index"
           )

    create index(:violations, [:violation_sequence], name: "violations_sequence_index")

    create index(:violations, [:case_reference], name: "violations_case_reference_index")

    create index(:violations, [:case_id], name: "violations_case_id_index")

    create unique_index(:violations, [:case_reference],
             name: "violations_unique_case_reference_index"
           )

    create unique_index(:violations, [:case_id, :violation_sequence],
             name: "violations_unique_case_sequence_index"
           )
  end

  def down do
    drop_if_exists unique_index(:violations, [:case_id, :violation_sequence],
                     name: "violations_unique_case_sequence_index"
                   )

    drop_if_exists unique_index(:violations, [:case_reference],
                     name: "violations_unique_case_reference_index"
                   )

    drop constraint(:violations, "violations_case_id_fkey")

    drop_if_exists index(:violations, [:case_id], name: "violations_case_id_index")

    drop_if_exists index(:violations, [:case_reference], name: "violations_case_reference_index")

    drop_if_exists index(:violations, [:violation_sequence], name: "violations_sequence_index")

    drop_if_exists index(:violations, [:case_id, :violation_sequence],
                     name: "violations_case_sequence_index"
                   )

    drop_if_exists index(:violations, [:case_reference], name: "violations_case_reference_unique")

    drop table(:violations)
  end
end
