defmodule EhsEnforcement.Repo.Migrations.AddUniqueRegulatorPerAgencyConstraint do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists unique_index(:notices, [:airtable_id],
                     name: "notices_unique_airtable_id_index"
                   )

    create unique_index(:notices, [:regulator_id, :agency_id],
             name: "notices_unique_regulator_per_agency_index",
             where: "(regulator_id IS NOT NULL AND regulator_id != '')"
           )
  end

  def down do
    drop_if_exists unique_index(:notices, [:regulator_id, :agency_id],
                     name: "notices_unique_regulator_per_agency_index"
                   )

    create unique_index(:notices, [:airtable_id],
             name: "notices_unique_airtable_id_index",
             where: "(airtable_id IS NOT NULL)"
           )
  end
end
