defmodule EhsEnforcement.Repo.Migrations.FixNoticeSchema do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create_if_not_exists table(:users, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :email, :citext, null: false
      add :github_id, :text
      add :github_login, :text
      add :name, :text
      add :avatar_url, :text
      add :github_url, :text
      add :is_admin, :boolean, default: false
      add :admin_checked_at, :utc_datetime_usec
      add :last_login_at, :utc_datetime_usec
      add :primary_provider, :text, default: "github"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:users, [:email], name: "users_unique_email_index")

    create_if_not_exists table(:user_identities, primary_key: false) do
      add :refresh_token, :text
      add :access_token_expires_at, :utc_datetime_usec
      add :access_token, :text
      add :uid, :text, null: false
      add :strategy, :text, null: false
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :user_id,
          references(:users,
            column: :id,
            name: "user_identities_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:user_identities, [:strategy, :uid, :user_id],
             name: "user_identities_unique_on_strategy_and_uid_and_user_id_index"
           )

    create_if_not_exists table(:tokens, primary_key: false) do
      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :extra_data, :map
      add :purpose, :text, null: false
      add :expires_at, :utc_datetime, null: false
      add :subject, :text, null: false
      add :jti, :text, null: false, primary_key: true
    end

    alter table(:notices) do
      add_if_not_exists :offence_action_type, :text
      add_if_not_exists :offence_action_date, :date
      add_if_not_exists :offence_breaches, :text
      add_if_not_exists :url, :text
    end

    alter table(:cases) do
      add_if_not_exists :offence_action_type, :text
      add_if_not_exists :url, :text
    end
  end

  def down do
    alter table(:cases) do
      remove_if_exists :url, :text
      remove_if_exists :offence_action_type, :text
    end

    alter table(:notices) do
      remove_if_exists :url, :text
      remove_if_exists :offence_breaches, :text
      remove_if_exists :offence_action_date, :date
      remove_if_exists :offence_action_type, :text
    end

    drop table(:tokens)

    drop_if_exists unique_index(:user_identities, [:strategy, :uid, :user_id],
                     name: "user_identities_unique_on_strategy_and_uid_and_user_id_index"
                   )

    drop constraint(:user_identities, "user_identities_user_id_fkey")

    drop table(:user_identities)

    drop_if_exists unique_index(:users, [:email], name: "users_unique_email_index")

    drop table(:users)
  end
end
