defmodule EhsEnforcement.Repo.Migrations.CreateLegislationAndOffencesTables do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # Enable pg_trgm extension for trigram indexing
    execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    
    create table(:offences, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :offence_description, :text
      add :offence_reference, :text
      add :legislation_part, :text
      add :fine, :decimal
      add :sequence_number, :bigint

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :case_id,
          references(:cases,
            column: :id,
            name: "offences_case_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :notice_id,
          references(:notices,
            column: :id,
            name: "offences_notice_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :legislation_id, :uuid, null: false
    end

    execute("CREATE INDEX offences_legislation_part_gin_trgm ON offences USING GIN (legislation_part gin_trgm_ops)")
    execute("CREATE INDEX offences_reference_gin_trgm ON offences USING GIN (offence_reference gin_trgm_ops)")
    execute("CREATE INDEX offences_description_gin_trgm ON offences USING GIN (offence_description gin_trgm_ops)")

    create index(:offences, [:offence_reference],
             name: "offences_reference_unique",
             unique: true,
             where: "offence_reference IS NOT NULL"
           )

    create index(:offences, [:sequence_number], name: "offences_sequence_index")

    create index(:offences, [:fine], name: "offences_fine_index")

    create index(:offences, [:legislation_id, :fine], name: "offences_legislation_fine_index")

    create index(:offences, [:case_id, :sequence_number], name: "offences_case_sequence_index")

    create index(:offences, [:legislation_id], name: "offences_legislation_id_index")

    create index(:offences, [:notice_id], name: "offences_notice_id_index")

    create index(:offences, [:case_id], name: "offences_case_id_index")

    create table(:legislation, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:offences) do
      modify :legislation_id,
             references(:legislation,
               column: :id,
               name: "offences_legislation_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:offences, [:case_id, :sequence_number],
             name: "offences_unique_case_sequence_index",
             where: "(case_id IS NOT NULL AND sequence_number IS NOT NULL)"
           )

    create unique_index(:offences, [:offence_reference],
             name: "offences_unique_offence_reference_index",
             where: "(offence_reference IS NOT NULL)"
           )

    alter table(:legislation) do
      add :legislation_title, :text, null: false
      add :legislation_year, :bigint
      add :legislation_number, :bigint
      add :legislation_type, :text, null: false, default: "act"

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    execute("CREATE INDEX legislation_title_gin_trgm ON legislation USING GIN (legislation_title gin_trgm_ops)")

    create index(:legislation, [:legislation_year], name: "legislation_year_index")

    create index(:legislation, [:legislation_type], name: "legislation_type_index")

    create index(:legislation, [:legislation_title, :legislation_year, :legislation_number],
             name: "legislation_title_year_number_unique",
             unique: true
           )

    create unique_index(
             :legislation,
             [:legislation_title, :legislation_year, :legislation_number],
             name: "legislation_unique_legislation_index"
           )
  end

  def down do
    drop_if_exists unique_index(
                     :legislation,
                     [:legislation_title, :legislation_year, :legislation_number],
                     name: "legislation_unique_legislation_index"
                   )

    drop_if_exists index(
                     :legislation,
                     [:legislation_title, :legislation_year, :legislation_number],
                     name: "legislation_title_year_number_unique"
                   )

    drop_if_exists index(:legislation, [:legislation_type], name: "legislation_type_index")

    drop_if_exists index(:legislation, [:legislation_year], name: "legislation_year_index")

    execute("DROP INDEX IF EXISTS legislation_title_gin_trgm")

    alter table(:legislation) do
      remove :updated_at
      remove :created_at
      remove :legislation_type
      remove :legislation_number
      remove :legislation_year
      remove :legislation_title
    end

    drop_if_exists unique_index(:offences, [:offence_reference],
                     name: "offences_unique_offence_reference_index"
                   )

    drop_if_exists unique_index(:offences, [:case_id, :sequence_number],
                     name: "offences_unique_case_sequence_index"
                   )

    drop constraint(:offences, "offences_legislation_id_fkey")

    alter table(:offences) do
      modify :legislation_id, :uuid
    end

    drop table(:legislation)

    drop constraint(:offences, "offences_case_id_fkey")

    drop constraint(:offences, "offences_notice_id_fkey")

    drop_if_exists index(:offences, [:case_id], name: "offences_case_id_index")

    drop_if_exists index(:offences, [:notice_id], name: "offences_notice_id_index")

    drop_if_exists index(:offences, [:legislation_id], name: "offences_legislation_id_index")

    drop_if_exists index(:offences, [:case_id, :sequence_number],
                     name: "offences_case_sequence_index"
                   )

    drop_if_exists index(:offences, [:legislation_id, :fine],
                     name: "offences_legislation_fine_index"
                   )

    drop_if_exists index(:offences, [:fine], name: "offences_fine_index")

    drop_if_exists index(:offences, [:sequence_number], name: "offences_sequence_index")

    drop_if_exists index(:offences, [:offence_reference], name: "offences_reference_unique")

    execute("DROP INDEX IF EXISTS offences_description_gin_trgm")
    execute("DROP INDEX IF EXISTS offences_reference_gin_trgm")  
    execute("DROP INDEX IF EXISTS offences_legislation_part_gin_trgm")

    drop table(:offences)
    
    # Note: We don't drop pg_trgm extension as it may be used by other tables
    # execute("DROP EXTENSION IF EXISTS pg_trgm")
  end
end
