defmodule EhsEnforcement.Repo.Migrations.AddUniqueRegulatorIdConstraint do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:cases, [:regulator_id], name: "cases_unique_regulator_id_index")
  end

  def down do
    drop_if_exists unique_index(:cases, [:regulator_id], name: "cases_unique_regulator_id_index")
  end
end
