defmodule EhsEnforcement.Repo.Migrations.AddCasesExistCurrentPage do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:scrape_sessions) do
      add :cases_exist_current_page, :bigint, default: 0
    end
  end

  def down do
    alter table(:scrape_sessions) do
      remove :cases_exist_current_page
    end
  end
end
