defmodule EhsEnforcement.Repo.Migrations.AddEaNoticeFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:notices) do
      add :regulator_event_reference, :text
      add :environmental_impact, :text
      add :environmental_receptor, :text
      add :legal_act, :text
      add :legal_section, :text
      add :regulator_function, :text
    end
  end

  def down do
    alter table(:notices) do
      remove :regulator_function
      remove :legal_section
      remove :legal_act
      remove :environmental_receptor
      remove :environmental_impact
      remove :regulator_event_reference
    end
  end
end
