defmodule EhsEnforcement.Repo.Migrations.AddEndPageToScrapeSessions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:scrape_sessions) do
      add :end_page, :bigint
    end
  end

  def down do
    alter table(:scrape_sessions) do
      remove :end_page
    end
  end
end
