defmodule EhsEnforcement.Repo.Migrations.AddMetricsFkIndexes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:metrics, [:legislation_id], name: "metrics_legislation_id_idx")

    create index(:metrics, [:offender_id], name: "metrics_offender_id_idx")

    create index(:metrics, [:agency_id], name: "metrics_agency_id_idx")
  end

  def down do
    drop_if_exists index(:metrics, [:agency_id], name: "metrics_agency_id_idx")

    drop_if_exists index(:metrics, [:offender_id], name: "metrics_offender_id_idx")

    drop_if_exists index(:metrics, [:legislation_id], name: "metrics_legislation_id_idx")
  end
end
