defmodule EhsEnforcement.Repo.Migrations.AddSicCodeToOffenders do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:offenders) do
      add :sic_code, :text
    end
  end

  def down do
    alter table(:offenders) do
      remove :sic_code
    end
  end
end
