defmodule EhsEnforcement.Repo.Migrations.AddAgenciesGinIndex do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:offenders, [:agencies], name: "offenders_agencies_gin", using: "GIN")
  end

  def down do
    drop_if_exists index(:offenders, [:agencies], name: "offenders_agencies_gin")
  end
end
