defmodule EhsEnforcement.Repo.Migrations.AddScrapingConfig do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:scraping_configs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :is_active, :boolean, null: false, default: true
      add :hse_base_url, :text, null: false, default: "https://www.hse.gov.uk"
      add :hse_database, :text, null: false, default: "convictions"
      add :requests_per_minute, :bigint, null: false, default: 10
      add :network_timeout_ms, :bigint, null: false, default: 30000
      add :pause_between_pages_ms, :bigint, null: false, default: 3000
      add :consecutive_existing_threshold, :bigint, null: false, default: 10
      add :max_pages_per_session, :bigint, null: false, default: 100
      add :max_consecutive_errors, :bigint, null: false, default: 3
      add :batch_size, :bigint, null: false, default: 50
      add :scheduled_scraping_enabled, :boolean, null: false, default: true
      add :manual_scraping_enabled, :boolean, null: false, default: true
      add :real_time_progress_enabled, :boolean, null: false, default: true
      add :admin_notifications_enabled, :boolean, null: false, default: true
      add :daily_scrape_cron, :text, default: "0 2 * * *"
      add :weekly_scrape_cron, :text, default: "0 1 * * 0"
      add :description, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:scraping_configs, [:name], name: "scraping_configs_unique_name_index")
  end

  def down do
    drop_if_exists unique_index(:scraping_configs, [:name],
                     name: "scraping_configs_unique_name_index"
                   )

    drop table(:scraping_configs)
  end
end
