defmodule EhsEnforcement.Repo.Migrations.AddMetricsResource do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:metrics, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :period, :text, null: false
      add :period_label, :text, null: false
      add :days_ago, :bigint, null: false
      add :recent_cases_count, :bigint, null: false, default: 0
      add :recent_notices_count, :bigint, null: false, default: 0
      add :total_cases_count, :bigint, null: false, default: 0
      add :total_notices_count, :bigint, null: false, default: 0
      add :total_fines_amount, :decimal, null: false, default: "0"
      add :active_agencies_count, :bigint, null: false, default: 0
      add :agency_stats, :map, null: false, default: %{}
      add :calculated_at, :utc_datetime_usec, null: false
      add :calculated_by, :text, null: false
      add :cutoff_date, :date, null: false
    end
  end

  def down do
    drop table(:metrics)
  end
end
