defmodule EhsEnforcement.Repo.Migrations.AddOffenderMatchReviews do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:offender_match_reviews, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :searched_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :confidence_score, :float, null: false
      add :candidate_companies, {:array, :map}, null: false, default: []
      add :status, :text, null: false, default: "pending"
      add :reviewed_at, :utc_datetime_usec
      add :selected_company_number, :text
      add :review_notes, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :offender_id,
          references(:offenders,
            column: :id,
            name: "offender_match_reviews_offender_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :reviewed_by_id,
          references(:users,
            column: :id,
            name: "offender_match_reviews_reviewed_by_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create index(:offender_match_reviews, [:status, :confidence_score, :searched_at])

    create index(:offender_match_reviews, [:reviewed_by_id], where: "reviewed_by_id IS NOT NULL")

    create index(:offender_match_reviews, [:offender_id])

    create index(:offender_match_reviews, [:status], where: "status = 'pending'")
  end

  def down do
    drop constraint(:offender_match_reviews, "offender_match_reviews_offender_id_fkey")

    drop constraint(:offender_match_reviews, "offender_match_reviews_reviewed_by_id_fkey")

    drop_if_exists index(:offender_match_reviews, [:status])

    drop_if_exists index(:offender_match_reviews, [:offender_id])

    drop_if_exists index(:offender_match_reviews, [:reviewed_by_id])

    drop_if_exists index(:offender_match_reviews, [:status, :confidence_score, :searched_at])

    drop table(:offender_match_reviews)
  end
end
