defmodule EhsEnforcement.Repo.Migrations.AddEaFieldsToCases do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:cases) do
      add :ea_event_reference, :text
      add :ea_total_violation_count, :bigint
      add :environmental_impact, :text
      add :environmental_receptor, :text
      add :is_ea_multi_violation, :boolean, default: false
    end
  end

  def down do
    alter table(:cases) do
      remove :is_ea_multi_violation
      remove :environmental_receptor
      remove :environmental_impact
      remove :ea_total_violation_count
      remove :ea_event_reference
    end
  end
end
