defmodule EhsEnforcement.Repo.Migrations.AddMetricsFilterDimensions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:metrics) do
      add :agency_id, :uuid
      add :record_type, :text
      add :offender_id, :uuid
      add :legislation_id, :uuid
      add :total_offences_count, :bigint, null: false, default: 0
      add :total_costs_amount, :decimal, null: false, default: "0"
      add :offender_breakdown, :map, null: false, default: %{}
      add :legislation_breakdown, :map, null: false, default: %{}
      add :recent_activity, {:array, :map}, null: false, default: []
    end

    create unique_index(
             :metrics,
             [:period, :agency_id, :record_type, :offender_id, :legislation_id],
             name: "metrics_unique_filter_combination_index"
           )

    drop_if_exists unique_index(
                     :legislation,
                     [:legislation_title, :legislation_year, :legislation_number],
                     name: "legislation_unique_legislation_index"
                   )

    create unique_index(
             :legislation,
             [:legislation_title, :legislation_year, :legislation_number],
             name: "legislation_unique_legislation_index",
             nulls_distinct: false
           )

    create unique_index(:legislation, [:legislation_title, :legislation_year],
             name: "legislation_unique_title_year_index",
             nulls_distinct: false
           )
  end

  def down do
    drop_if_exists unique_index(:legislation, [:legislation_title, :legislation_year],
                     name: "legislation_unique_title_year_index"
                   )

    drop_if_exists unique_index(
                     :legislation,
                     [:legislation_title, :legislation_year, :legislation_number],
                     name: "legislation_unique_legislation_index"
                   )

    create unique_index(
             :legislation,
             [:legislation_title, :legislation_year, :legislation_number],
             name: "legislation_unique_legislation_index"
           )

    drop_if_exists unique_index(
                     :metrics,
                     [:period, :agency_id, :record_type, :offender_id, :legislation_id],
                     name: "metrics_unique_filter_combination_index"
                   )

    alter table(:metrics) do
      remove :recent_activity
      remove :legislation_breakdown
      remove :offender_breakdown
      remove :total_costs_amount
      remove :total_offences_count
      remove :legislation_id
      remove :offender_id
      remove :record_type
      remove :agency_id
    end
  end
end
