defmodule EhsEnforcement.Repo.Migrations.AddEnrichmentTables do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:enrichments, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :regulation_links, {:array, :map}
      add :benchmark_analysis, :map
      add :pattern_detection, :map
      add :layperson_summary, :text
      add :professional_summary, :text
      add :auto_tags, {:array, :text}, default: []
      add :confidence_scores, :map
      add :model_version, :text, null: false

      add :generated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :processing_time_ms, :bigint

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :case_id,
          references(:cases,
            column: :id,
            name: "enrichments_case_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :notice_id,
          references(:notices,
            column: :id,
            name: "enrichments_notice_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create index(:enrichments, [:confidence_scores],
             name: "enrichments_confidence_scores_gin",
             using: "GIN"
           )

    create index(:enrichments, [:benchmark_analysis],
             name: "enrichments_benchmark_analysis_gin",
             using: "GIN"
           )

    create index(:enrichments, [:regulation_links],
             name: "enrichments_regulation_links_gin",
             using: "GIN"
           )

    # Note: Cannot use NOW() in index predicate (not immutable)
    # Removing partial index for recent enrichments - can filter at query time instead
    create index(:enrichments, [:generated_at], name: "enrichments_generated_at_index")

    create index(:enrichments, [:model_version], name: "enrichments_model_version_index")

    create index(:enrichments, [:notice_id], name: "enrichments_notice_id_index")

    create index(:enrichments, [:case_id], name: "enrichments_case_id_index")

    # XOR constraint: exactly one parent (case_id XOR notice_id)
    create constraint(:enrichments, :must_have_one_parent,
             check: "(case_id IS NOT NULL AND notice_id IS NULL) OR (case_id IS NULL AND notice_id IS NOT NULL)"
           )

    create table(:enrichment_validations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :section, :text, null: false
      add :rating, :bigint, null: false
      add :corrections, :text

      add :validated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :validation_notes, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :enrichment_id,
          references(:enrichments,
            column: :id,
            name: "enrichment_validations_enrichment_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "enrichment_validations_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create index(:enrichment_validations, [:rating],
             name: "enrichment_validations_high_rating_index",
             where: "rating >= 4"
           )

    create index(:enrichment_validations, [:user_id, :validated_at],
             name: "enrichment_validations_user_date_index"
           )

    create index(:enrichment_validations, [:enrichment_id, :section],
             name: "enrichment_validations_enrichment_section_index"
           )

    create index(:enrichment_validations, [:section],
             name: "enrichment_validations_section_index"
           )

    create index(:enrichment_validations, [:user_id],
             name: "enrichment_validations_user_id_index"
           )

    create index(:enrichment_validations, [:enrichment_id],
             name: "enrichment_validations_enrichment_id_index"
           )

    create unique_index(:enrichment_validations, [:enrichment_id, :user_id, :section],
             name: "enrichment_validations_unique_validation_per_section_index",
             where: "(enrichment_id IS NOT NULL AND user_id IS NOT NULL AND section IS NOT NULL)"
           )

    # Rating range constraint
    create constraint(:enrichment_validations, :rating_range,
             check: "rating >= 1 AND rating <= 5"
           )
  end

  def down do
    # Drop constraints first
    drop constraint(:enrichment_validations, :rating_range)

    drop_if_exists unique_index(:enrichment_validations, [:enrichment_id, :user_id, :section],
                     name: "enrichment_validations_unique_validation_per_section_index"
                   )

    drop constraint(:enrichment_validations, "enrichment_validations_enrichment_id_fkey")

    drop constraint(:enrichment_validations, "enrichment_validations_user_id_fkey")

    drop_if_exists index(:enrichment_validations, [:enrichment_id],
                     name: "enrichment_validations_enrichment_id_index"
                   )

    drop_if_exists index(:enrichment_validations, [:user_id],
                     name: "enrichment_validations_user_id_index"
                   )

    drop_if_exists index(:enrichment_validations, [:section],
                     name: "enrichment_validations_section_index"
                   )

    drop_if_exists index(:enrichment_validations, [:enrichment_id, :section],
                     name: "enrichment_validations_enrichment_section_index"
                   )

    drop_if_exists index(:enrichment_validations, [:user_id, :validated_at],
                     name: "enrichment_validations_user_date_index"
                   )

    drop_if_exists index(:enrichment_validations, [:rating],
                     name: "enrichment_validations_high_rating_index"
                   )

    drop table(:enrichment_validations)

    # Drop enrichments constraints
    drop constraint(:enrichments, :must_have_one_parent)

    drop constraint(:enrichments, "enrichments_case_id_fkey")

    drop constraint(:enrichments, "enrichments_notice_id_fkey")

    drop_if_exists index(:enrichments, [:case_id], name: "enrichments_case_id_index")

    drop_if_exists index(:enrichments, [:notice_id], name: "enrichments_notice_id_index")

    drop_if_exists index(:enrichments, [:model_version], name: "enrichments_model_version_index")

    drop_if_exists index(:enrichments, [:generated_at], name: "enrichments_generated_at_index")

    drop_if_exists index(:enrichments, [:regulation_links],
                     name: "enrichments_regulation_links_gin"
                   )

    drop_if_exists index(:enrichments, [:benchmark_analysis],
                     name: "enrichments_benchmark_analysis_gin"
                   )

    drop_if_exists index(:enrichments, [:confidence_scores],
                     name: "enrichments_confidence_scores_gin"
                   )

    drop table(:enrichments)
  end
end
