defmodule EhsEnforcement.Repo.Migrations.AddCaseProcessingResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:scraped_cases, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :session_id, :text, null: false
      add :regulator_id, :text, null: false
      add :page, :bigint, null: false
      add :offender_name, :text
      add :offence_action_date, :date
      add :offence_fine, :decimal
      add :offence_result, :text
      add :processing_status, :text, default: "scraping"
      add :database_status, :text, default: "pending"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:scraped_cases, [:session_id, :regulator_id, :page],
             name: "scraped_cases_unique_case_per_session_index"
           )

    create table(:case_processing_logs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :session_id, :text, null: false
      add :page, :bigint, null: false
      add :cases_scraped, :bigint, default: 0
      add :cases_created, :bigint, default: 0
      add :cases_existing, :bigint, default: 0
      add :creation_errors, {:array, :text}, default: []
      add :scraped_case_summary, {:array, :map}, default: []

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop table(:case_processing_logs)

    drop_if_exists unique_index(:scraped_cases, [:session_id, :regulator_id, :page],
                     name: "scraped_cases_unique_case_per_session_index"
                   )

    drop table(:scraped_cases)
  end
end
