defmodule EhsEnforcement.Repo.Migrations.AddPerformanceIndexes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:notices, [:agency_id, :offence_action_date], name: "notices_agency_date_index")

    create index(:notices, [:agency_id], name: "notices_agency_id_index")

    create index(:notices, [:offence_action_date], name: "notices_offence_action_date_index")

    create index(:cases, [:agency_id, :offence_action_date], name: "cases_agency_date_index")

    create index(:cases, [:agency_id], name: "cases_agency_id_index")

    create index(:cases, [:offence_action_date], name: "cases_offence_action_date_index")
  end

  def down do
    drop_if_exists index(:cases, [:offence_action_date], name: "cases_offence_action_date_index")

    drop_if_exists index(:cases, [:agency_id], name: "cases_agency_id_index")

    drop_if_exists index(:cases, [:agency_id, :offence_action_date],
                     name: "cases_agency_date_index"
                   )

    drop_if_exists index(:notices, [:offence_action_date],
                     name: "notices_offence_action_date_index"
                   )

    drop_if_exists index(:notices, [:agency_id], name: "notices_agency_id_index")

    drop_if_exists index(:notices, [:agency_id, :offence_action_date],
                     name: "notices_agency_date_index"
                   )
  end
end
