defmodule EhsEnforcement.Repo.Migrations.UpdateOffenderIdentityConstraints do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists unique_index(:offenders, [:normalized_name, :postcode],
                     name: "offenders_unique_name_postcode_index"
                   )

    create unique_index(:offenders, [:company_registration_number],
             name: "offenders_unique_company_number_index",
             where:
               "(company_registration_number IS NOT NULL AND\ncompany_registration_number != ''\n)"
           )

    create unique_index(:offenders, [:normalized_name],
             name: "offenders_unique_name_index",
             where: "(company_registration_number IS NULL OR\ncompany_registration_number = ''\n)"
           )
  end

  def down do
    drop_if_exists unique_index(:offenders, [:normalized_name],
                     name: "offenders_unique_name_index"
                   )

    drop_if_exists unique_index(:offenders, [:company_registration_number],
                     name: "offenders_unique_company_number_index"
                   )

    create unique_index(:offenders, [:normalized_name, :postcode],
             name: "offenders_unique_name_postcode_index"
           )
  end
end
