defmodule EhsEnforcement.Repo.Migrations.CreateUnifiedProcessingLog do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:processing_logs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :session_id, :text, null: false
      add :agency, :text, null: false
      add :batch_or_page, :bigint, default: 1
      add :items_found, :bigint, default: 0
      add :items_created, :bigint, default: 0
      add :items_existing, :bigint, default: 0
      add :items_failed, :bigint, default: 0
      add :creation_errors, {:array, :text}, default: []
      add :scraped_items, {:array, :map}, default: []

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop table(:processing_logs)
  end
end
