defmodule EhsEnforcement.Repo.Migrations.AddPerPageTrackingToScrapeSessions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:scrape_sessions) do
      add :cases_created_current_page, :bigint, default: 0
      add :cases_updated, :bigint, default: 0
      add :cases_updated_current_page, :bigint, default: 0
    end
  end

  def down do
    alter table(:scrape_sessions) do
      remove :cases_updated_current_page
      remove :cases_updated
      remove :cases_created_current_page
    end
  end
end
