defmodule EhsEnforcement.Repo.Migrations.AddMissingIndexes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:notices, [:offence_breaches], name: "notices_offence_breaches_index")

    create index(:notices, [:offence_action_type], name: "notices_offence_action_type_index")

    create index(:notices, [:regulator_id], name: "notices_regulator_id_index")

    create index(:cases, [:offence_breaches], name: "cases_offence_breaches_index")

    create index(:cases, [:regulator_id], name: "cases_regulator_id_index")

    create index(:cases, [:offence_fine], name: "cases_offence_fine_index")
  end

  def down do
    drop_if_exists index(:cases, [:offence_fine], name: "cases_offence_fine_index")

    drop_if_exists index(:cases, [:regulator_id], name: "cases_regulator_id_index")

    drop_if_exists index(:cases, [:offence_breaches], name: "cases_offence_breaches_index")

    drop_if_exists index(:notices, [:regulator_id], name: "notices_regulator_id_index")

    drop_if_exists index(:notices, [:offence_action_type],
                     name: "notices_offence_action_type_index"
                   )

    drop_if_exists index(:notices, [:offence_breaches], name: "notices_offence_breaches_index")
  end
end
