defmodule EhsEnforcement.Repo.Migrations.AddCasesProcessedToScrapeSessions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:scrape_sessions) do
      add :cases_processed, :bigint, default: 0
    end
  end

  def down do
    alter table(:scrape_sessions) do
      remove :cases_processed
    end
  end
end
