defmodule EhsEnforcement.Repo.Migrations.AddExtendedSyncResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:ehs_sync_sessions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :session_id, :text, null: false
      add :sync_type, :text, null: false
      add :target_resource, :text, null: false
      add :source_adapter, :text, null: false
      add :status, :text, null: false, default: "pending"
      add :progress_stats, :map, default: %{}
      add :started_at, :utc_datetime_usec
      add :completed_at, :utc_datetime_usec
      add :duration_ms, :bigint
      add :config, :map, default: %{}
      add :metadata, :map, default: %{}
      add :initiated_by, :text
      add :estimated_total, :bigint
      add :actual_total, :bigint
      add :error_count, :bigint, default: 0
      add :error_details, :map, default: %{}
      add :last_error, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:ehs_sync_logs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :sync_session_id,
          references(:ehs_sync_sessions,
            column: :id,
            name: "ehs_sync_logs_sync_session_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :session_id, :text, null: false
      add :sync_batch_id, :uuid
      add :level, :text, null: false
      add :event_type, :text, null: false
      add :message, :text, null: false
      add :event_data, :map, default: %{}
      add :source_record_id, :text
      add :error_details, :map, default: %{}
      add :duration_ms, :bigint
      add :occurred_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:ehs_sync_batches, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:ehs_sync_logs) do
      modify :sync_batch_id,
             references(:ehs_sync_batches,
               column: :id,
               name: "ehs_sync_logs_sync_batch_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:ehs_sync_batches) do
      add :sync_session_id,
          references(:ehs_sync_sessions,
            column: :id,
            name: "ehs_sync_batches_sync_session_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :session_id, :text, null: false
      add :batch_number, :bigint, null: false
      add :batch_size, :bigint, null: false
      add :status, :text, null: false, default: "pending"
      add :source_ids, {:array, :text}, default: []
      add :records_processed, :bigint, default: 0
      add :records_created, :bigint, default: 0
      add :records_updated, :bigint, default: 0
      add :records_failed, :bigint, default: 0
      add :records_skipped, :bigint, default: 0
      add :started_at, :utc_datetime_usec
      add :completed_at, :utc_datetime_usec
      add :processing_time_ms, :bigint
      add :error_details, :map, default: %{}
      add :batch_metadata, :map, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop constraint(:ehs_sync_batches, "ehs_sync_batches_sync_session_id_fkey")

    alter table(:ehs_sync_batches) do
      remove :updated_at
      remove :inserted_at
      remove :batch_metadata
      remove :error_details
      remove :processing_time_ms
      remove :completed_at
      remove :started_at
      remove :records_skipped
      remove :records_failed
      remove :records_updated
      remove :records_created
      remove :records_processed
      remove :source_ids
      remove :status
      remove :batch_size
      remove :batch_number
      remove :session_id
      remove :sync_session_id
    end

    drop constraint(:ehs_sync_logs, "ehs_sync_logs_sync_batch_id_fkey")

    alter table(:ehs_sync_logs) do
      modify :sync_batch_id, :uuid
    end

    drop table(:ehs_sync_batches)

    drop constraint(:ehs_sync_logs, "ehs_sync_logs_sync_session_id_fkey")

    drop table(:ehs_sync_logs)

    drop table(:ehs_sync_sessions)
  end
end
