defmodule EhsEnforcement.Repo.Migrations.DropOffenceBreachesColumn do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists index(:notices, [:offence_breaches], name: "notices_offence_breaches_gin_trgm")

    drop_if_exists index(:notices, [:offence_breaches], name: "notices_offence_breaches_index")

    alter table(:notices) do
      remove :offence_breaches
    end
  end

  def down do
    alter table(:notices) do
      add :offence_breaches, :text
    end

    create index(:notices, [:offence_breaches], name: "notices_offence_breaches_index")

    create index(:notices, [:offence_breaches],
             name: "notices_offence_breaches_gin_trgm",
             using: "GIN"
           )
  end
end
