defmodule EhsEnforcement.Repo.Migrations.AddUniqueOffenderConstraintToReviews do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists index(:offender_match_reviews, [:offender_id])

    create index(:offender_match_reviews, [:offender_id],
             name: "offender_match_reviews_offender_id_index",
             unique: true
           )
  end

  def down do
    drop_if_exists index(:offender_match_reviews, [:offender_id],
                     name: "offender_match_reviews_offender_id_index"
                   )

    create index(:offender_match_reviews, [:offender_id])
  end
end
