defmodule EhsEnforcement.Repo.Migrations.RenameAirtableIdToCaseReferenceAndCompositeKey do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists unique_index(:cases, [:airtable_id], name: "cases_unique_airtable_id_index")

    rename table(:cases), :airtable_id, to: :case_reference

    drop_if_exists unique_index(:cases, [:regulator_id], name: "cases_unique_regulator_id_index")

    create unique_index(:cases, [:agency_id, :regulator_id],
             name: "cases_unique_case_per_agency_index"
           )

    create unique_index(:cases, [:case_reference],
             name: "cases_unique_case_reference_index",
             where: "(case_reference IS NOT NULL)"
           )
  end

  def down do
    drop_if_exists unique_index(:cases, [:case_reference],
                     name: "cases_unique_case_reference_index"
                   )

    drop_if_exists unique_index(:cases, [:agency_id, :regulator_id],
                     name: "cases_unique_case_per_agency_index"
                   )

    create unique_index(:cases, [:regulator_id], name: "cases_unique_regulator_id_index")

    rename table(:cases), :case_reference, to: :airtable_id

    create unique_index(:cases, [:airtable_id],
             name: "cases_unique_airtable_id_index",
             where: "(airtable_id IS NOT NULL)"
           )
  end
end
