defmodule EhsEnforcement.Repo.Migrations.AddAddressCountryToOffenders do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:offenders) do
      add :address, :text
      add :country, :text
    end
  end

  def down do
    alter table(:offenders) do
      remove :country
      remove :address
    end
  end
end
