defmodule EhsEnforcement.Repo.Migrations.CreateScrapeSessions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:scrape_sessions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :session_id, :text, null: false
      add :start_page, :bigint, null: false, default: 1
      add :max_pages, :bigint, null: false, default: 10
      add :database, :text, null: false, default: "convictions"
      add :status, :text, null: false, default: "pending"
      add :current_page, :bigint
      add :pages_processed, :bigint, default: 0
      add :cases_found, :bigint, default: 0
      add :cases_created, :bigint, default: 0
      add :cases_exist_total, :bigint, default: 0
      add :errors_count, :bigint, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:scrape_sessions, [:session_id],
             name: "scrape_sessions_unique_session_id_index"
           )
  end

  def down do
    drop_if_exists unique_index(:scrape_sessions, [:session_id],
                     name: "scrape_sessions_unique_session_id_index"
                   )

    drop table(:scrape_sessions)
  end
end
