defmodule EhsEnforcement.Repo.Migrations.AddOffenceBreachesToNotices do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:notices) do
      add :offence_breaches, :text
    end
  end

  def down do
    alter table(:notices) do
      remove :offence_breaches
    end
  end
end
